// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: imagehash.proto

package imagehash

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ImagehashService_GetHash_FullMethodName = "/imagehash.ImagehashService/GetHash"
)

// ImagehashServiceClient is the client API for ImagehashService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ImagehashServiceClient interface {
	GetHash(ctx context.Context, in *GetHashRequest, opts ...grpc.CallOption) (*GetHashResponse, error)
}

type imagehashServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewImagehashServiceClient(cc grpc.ClientConnInterface) ImagehashServiceClient {
	return &imagehashServiceClient{cc}
}

func (c *imagehashServiceClient) GetHash(ctx context.Context, in *GetHashRequest, opts ...grpc.CallOption) (*GetHashResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetHashResponse)
	err := c.cc.Invoke(ctx, ImagehashService_GetHash_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ImagehashServiceServer is the server API for ImagehashService service.
// All implementations must embed UnimplementedImagehashServiceServer
// for forward compatibility.
type ImagehashServiceServer interface {
	GetHash(context.Context, *GetHashRequest) (*GetHashResponse, error)
	mustEmbedUnimplementedImagehashServiceServer()
}

// UnimplementedImagehashServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedImagehashServiceServer struct{}

func (UnimplementedImagehashServiceServer) GetHash(context.Context, *GetHashRequest) (*GetHashResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHash not implemented")
}
func (UnimplementedImagehashServiceServer) mustEmbedUnimplementedImagehashServiceServer() {}
func (UnimplementedImagehashServiceServer) testEmbeddedByValue()                          {}

// UnsafeImagehashServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ImagehashServiceServer will
// result in compilation errors.
type UnsafeImagehashServiceServer interface {
	mustEmbedUnimplementedImagehashServiceServer()
}

func RegisterImagehashServiceServer(s grpc.ServiceRegistrar, srv ImagehashServiceServer) {
	// If the following call pancis, it indicates UnimplementedImagehashServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ImagehashService_ServiceDesc, srv)
}

func _ImagehashService_GetHash_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHashRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImagehashServiceServer).GetHash(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ImagehashService_GetHash_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImagehashServiceServer).GetHash(ctx, req.(*GetHashRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ImagehashService_ServiceDesc is the grpc.ServiceDesc for ImagehashService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ImagehashService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "imagehash.ImagehashService",
	HandlerType: (*ImagehashServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetHash",
			Handler:    _ImagehashService_GetHash_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "imagehash.proto",
}
